### ISSUE TITLE
install fails on CentOS 8 for failed dependancies: python3.6dist & python3-APScheduler

### ISSUE THREAD

**Issue by xpseudonym** [luminoso/fedora-copr-vorta#2]
Hmm, virgin territory :)

```
$ sudo dnf install vorta-0.7.8-1.el8.x86_64
Copr repo for vorta owned by luminoso                                                               6.7 kB/s | 3.3 kB     00:00    
Error: 
 Problem: conflicting requests
  - nothing provides python3.6dist(apscheduler) < 4.0 needed by vorta-0.7.8-1.el8.x86_64
  - nothing provides python3-APScheduler needed by vorta-0.7.8-1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
$ sudo dnf list python3.6dist
[sudo] password for admin: 
Last metadata expiration check: 0:15:41 ago on Tue 02 Nov 2021 09:07:14 GMT.
Error: No matching Packages to list
[admin@frontserver yum.repos.d]$ sudo dnf list python3-APScheduler
Last metadata expiration check: 0:16:05 ago on Tue 02 Nov 2021 09:07:14 GMT.
Error: No matching Packages to list
$
```
I had to enable fedora repos for the dependances:
```
$ sudo dnf install vorta-0.7.8-1.el8.x86_64
Warning: failed loading '/etc/yum.repos.d/79CentOS-Linux-Media.repo', skipping.
Last metadata expiration check: 0:00:52 ago on Tue 02 Nov 2021 09:35:30 GMT.
Dependencies resolved.
====================================================================================================================================
 Package                        Architecture    Version                Repository                                              Size
====================================================================================================================================
Installing:
 vorta                          x86_64          0.7.8-1.el8            copr:copr.fedorainfracloud.org:luminoso:vorta          448 k
Installing dependencies:
 python3-APScheduler            noarch          3.0.5-7.fc28           fedora28                                                85 k
 python3-appdirs                noarch          1.4.3-8.el8            epel                                                    23 k
 python3-jeepney                noarch          0.4.3-3.el8            epel                                                   1.6 M
 python3-peewee                 x86_64          3.14.4-3.el8           epel                                                   1.0 M
 python3-secretstorage          noarch          3.2.0-3.el8            epel                                                    37 k
 python3-tzlocal                noarch          1.5.1-2.fc28           fedora28                                                31 k

Transaction Summary
====================================================================================================================================
Install  7 Packages

Total download size: 3.2 M
Installed size: 12 M
Is this ok [y/N]:
```
Thanks
Morgan.
PS would you publish your PGP fingerprint on the copra home page please, apparently it's:
Fingerprint: 9815 824A B844 720F 441A CD2D 9847 6B2E 649C 3725

**Comment by luminoso** [comment]
A)
Humm I have to spin up a centos8 vm to check what's going on.
Probably centos python packages are way to old to have vorta installed in it.

B) Which fingerprint you're looking for? The package ones? They are generated by COPR system itself and I have no control of the signing process

**Comment by xpseudonym** [comment]
> B) Which fingerprint you're looking for? The package ones? They are generated by COPR system itself and I have no control of the signing process

Hmm, this fingerprint:
```
$ sudo dnf install vorta-0.7.8-1.el8.x86_64
...
(7/7): vorta-0.7.8-1.el8.x86_64.rpm                                                                 479 kB/s | 448 kB     00:00    
------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                               1.5 MB/s | 3.2 MB     00:02     
warning: /var/cache/dnf/copr:copr.fedorainfracloud.org:luminoso:vorta-ce8a7ca9ac1410d7/packages/vorta-0.7.8-1.el8.x86_64.rpm: Header V3 RSA/SHA1 Signature, key ID 649c3725: NOKEY
Copr repo for vorta owned by luminoso                                                               6.4 kB/s | 998  B     00:00    
Importing GPG key 0x649C3725:
 Userid     : "luminoso_vorta (None) <luminoso#vorta@copr.fedorahosted.org>"
 Fingerprint: 9815 824A B844 720F 441A CD2D 9847 6B2E 649C 3725
 From       : https://download.copr.fedorainfracloud.org/results/luminoso/vorta/pubkey.gpg
Is this ok [y/N]: y
Is this ok [y/N]: y
Key imported successfully
Running transaction check
...
```
I just figured that for the fingerprint is to be useful it needs to published somewhere trustworthy and I figured that'd be on your copr vorta page - I think the above is the repo fingerprint - I guess I could d/l the public key via https and generate the fingerprint from that and that should be trustworthy - but, that's a bit a fiasco.

**Comment by xpseudonym** [comment]
> A)
Humm I have to spin up a centos8 vm to check what's going on.
Probably centos python packages are way to old to have vorta installed in it.

I've ended up installing it via `pip3 install --user vorta` to root...  Which I suspect isn't the recommended thing to do :-/

This is what ended up being installed:
```
...
Successfully installed apscheduler-3.8.1 backports.zoneinfo-0.2.1 importlib-resources-5.4.0 pytz-deprecation-shim-0.1.0.post0 tzdata-2021.5 tzlocal-4.1 vorta-0.7.8 zipp-3.6.0
```
Which seems to work - I'm running it from my no gui home server via `$ ssh -Y root@frontserver`
Thanks

**Comment by luminoso** [comment]
I did indeed confirm your issue. I guess the best option is to disable CentOS 8 repos and provide COPR package for Fedora only.

No package provides natively apscheduler for centos 8 and I don't want to build yet another package

About the fingerprint, the only trustworthy place to share it is in the copr description page. But it is the system itself that generates it, so I see no purpose on doing that, unless you have any other suggestion

**Comment by xpseudonym** [comment]
Thanks - I wondered if that was the answer.  I'll stick with the pip install, it works.

Re the fingerprint, yes I guess if it's system-generated then it should be system-published too - and to the copr description page sound sensible.  Perhaps I'll file a bug somewhere because there's not much point generating a fingerprint if it can't be verified.  I wouldn't normally think about it with a standard repo - but, as it popped up and I thought the whole copr system is a little less formal I'd look for confirmation...
Thanks again, M
