### ISSUE TITLE
Problems on Fedora 35

### ISSUE THREAD

**Issue by eschruefer** [luminoso/fedora-copr-vorta#4]
On Fedora 35, vorta dumps core. The rpm one currently gets from the repo has vorta version 0.8. Version 0.82 obviously didn't build on copr. Could you please check?

**Comment by luminoso** [comment]
Will take a look into it. If you spotted something feel free to do a pull request

**Comment by luminoso** [comment]
Pushed a new update. Can you please check if it is working for you? Mine stopped crashing after a few seconds after opening

**Comment by eschruefer** [comment]
Version 0.8.2-2 works fine for me now. Thank you.
