### ISSUE TITLE
Vorta 0.8.4 for Fedora

### ISSUE THREAD

**Issue by eschruefer** [luminoso/fedora-copr-vorta#6]
Vorta 0.8.4 is not building on Fedora copr. Could you please check and also provide builds for Fedora 36?
Thanks.

**Comment by luminoso** [comment]
humm it looks like a copr problem. will take a look

**Comment by luminoso** [comment]
Fixed!

The copr repo was hitting this bug: https://pagure.io/copr/copr/issue/2202
Applied the workaround and it is building again.

Pushed and tested update for f36. Should be working now. If now, please ping!
